### ISSUE TITLE
Mistress Sass'zine - Concealing Murk

### ISSUE THREAD

**Issue by JoshYaxley** [JoshYaxley/Wipefest.EventConfigs#1]
Concealing Murk is cast when the Abyss Stalkers die. The timing of this is important, because it slows down any Slicing Tornadoes that pass through it, but only lasts for a short while. It is also often used as a damage source for dropping Delicious Bufferfish. It would be useful to be able to track this so that players can work out if they are killing the adds at the right time.

Here is a relevant Warcraft Logs filter for the event: https://www.warcraftlogs.com/reports/qvJQ7bFcm2XghrNH#fight=16&type=casts&hostility=1&source=237&pins=0%24Separate%24%23909049%24casts%241%240.0.0.Any%24115795.0.0.NPC%24true%240.0.0.Any%24false%24230950

Concealing Murk has a spell id of 230950.

There are a lot of casts of this throughout the fight, so it would make sense to either hide the event by default, or group close casts together into a single event. However, because the timing of this is important, grouping close events might lose some valuable information (unless the grouping range was fairly small).

**Comment by JoshYaxley2** [comment]
I've created a second account to demonstrate how someone might create a pull request to solve an issue. The first thing they should do is comment on the issue to let people know that they'll be working on it!

**Comment by JoshYaxley2** [comment]
#2

**Comment by JoshYaxley** [comment]
I've merged the pull request, and the change is now live!
