### ISSUE TITLE
Taunts

### ISSUE THREAD

**Issue by JoshYaxley** [JoshYaxley/Wipefest.EventConfigs#6]
It would be useful to be able to see who is taunting what, and when. Considerations:

1. This might result in a lot of events as Taunt is on a short cooldown
2. This functionality will probably be superseded when Player Overviews come in and people can focus on the tanks to see all their important abilities

**Comment by yajinni** [comment]
made into a pr: https://github.com/JoshYaxley/Wipefest.EventConfigs/pull/7

**Comment by yajinni** [comment]
Found out about the talent that pallys have that lets them AOE taunt when they bubble. Looking into any other wierd cases like this.
Also looking into adding maybe pet taunts since those are such a pain....
Will show test logs and then make a new PR for that.

**Comment by JoshYaxley** [comment]
Sounds good. Maybe don't include Summon Black Ox Statue as it isn't really a taunt until the Brewmaster casts Provoke on it. Again, we can provide more detail like that when Player Overviews are introduced!

**Comment by JoshYaxley** [comment]
Used your code to add taunts, but removed Black Ox Statue.

Ideally, I want to add taunt events (instead of ability events) so that they can simply read "X taunted Y" instead of "X cast Z on Y" but can get to that another time.

Thanks :)

**Comment by mrkmcknz** [comment]
@JoshYaxley This can be closed now?

**Comment by JoshYaxley** [comment]
Kind of. Wanted to add a new **eventType** so that the events can read "X taunted Y". That could also just be another issue. Also need to think of how the GitHub issues live alongside https://ideas.wipefest.net
